allowBuilds:
    esbuild: true
    sharp: true
onlyBuiltDependencies:
    - esbuild
    - sharp
supportedArchitectures:
    os:
        - current
    cpu:
        - current
    libc:
        - glibc
        - musl
